[platformio]
boards_dir = boards
default_envs = lilygo-t5-epaper-s3
src_dir = main

[env:lilygo-t5-epaper-s3]
platform = espressif32@6.12.0
framework = espidf
board = T5-ePaper-S3
upload_speed = 921600
monitor_speed = 115200
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
build_flags =
    -DBOARD_HAS_PSRAM
